regen

diff --git a/app/bitmap/Makefile.in b/app/bitmap/Makefile.in
--- a/app/bitmap/Makefile.in
+++ b/app/bitmap/Makefile.in
@@ -279,8 +279,10 @@ APPDEFAULTFILES = \
 
 SUFFIXES = .ad .$(APP_MAN_SUFFIX) .man
 appdefault_DATA = $(APPDEFAULTFILES)
-EXTRA_DIST = $(APPDEFAULTFILES:%=%.ad) bitmap.icon $(appman_PRE)
+EXTRA_DIST = $(APPDEFAULTFILES:%=%.ad) bitmap.icon ChangeLog \
+	autogen.sh $(appman_PRE)
 CLEANFILES = $(APPDEFAULTFILES) $(appman_DATA) $(BUILT_SOURCES)
+MAINTAINERCLEANFILES = ChangeLog
 
 # bitmaps
 bitmapdir = $(includedir)/X11/bitmaps
@@ -697,6 +699,9 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
+	$(MAKE) $(AM_MAKEFLAGS) \
+	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
+	  dist-hook
 	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
 	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
@@ -829,6 +834,7 @@ maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
 	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
+	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
 clean: clean-am
 
 clean-am: clean-binPROGRAMS clean-generic mostlyclean-am
@@ -886,8 +892,8 @@ uninstall-am: uninstall-appdefaultDATA uninstall-appmanDATA \
 
 .PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
 	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
-	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
-	distclean-compile distclean-generic distclean-hdr \
+	dist-gzip dist-hook dist-shar dist-tarZ dist-zip distcheck \
+	distclean distclean-compile distclean-generic distclean-hdr \
 	distclean-tags distcleancheck distdir distuninstallcheck dvi \
 	dvi-am html html-am info info-am install install-am \
 	install-appdefaultDATA install-appmanDATA install-binPROGRAMS \
@@ -903,6 +909,11 @@ uninstall-am: uninstall-appdefaultDATA uninstall-appmanDATA \
 
 .ad:
 	cp $< $@
+
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
 
 .man.$(APP_MAN_SUFFIX):
 	sed $(MAN_SUBSTS) < $< > $@
